### ISSUE TITLE
different budgets for different days

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#100]
we need to be able to input one par of budget (4m, 8m) for each day

**Comment by NobleKennamer** [comment]
I believe that the only thing that needs to change to make this possible is in the run_time_domain_active_learning_loop. Just make budgets a list of tuples with length equal to the number of nights, ie [(b_4m_1, b_8m_1), (b_4m_2, b_8m_2), ..., (b_4m_N, b_8m_N)], and then when you call  _get_indices_of_objects_to_be_queried just send it budgets[night] instead of budgets.

**Comment by emilleishida** [comment]
done
